package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.Qodana
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.qodana
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            id = "simpleRunner"
            scriptContent = """
                /bin/cat <<'EOM' >runner.sh
                            #!/bin/bash
                            cp /data/project/ui.sarif.json /data/results/qodana.sarif.json 
                            EOM
                            chmod +x runner.sh
            """.trimIndent()
        }
        qodana {
            name = "qodana"
            reportAsTests = true
            linter = customLinter {
                image = "jetbrains/qodana-jvm:2023.3"
            }
            additionalDockerArguments = """--entrypoint="/data/project/runner.sh""""
            param("report-as-test-mode", "each-inspection-is-test")
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                /bin/cat <<'EOM' >runner.sh
                            #!/bin/bash
                            cp /data/project/ui.sarif.json /data/results/qodana.sarif.json 
                            EOM
                            chmod 777 runner.sh
            """.trimIndent()
        }
        update<Qodana>(1) {
            clearConditions()
            inspectionProfile = default()
            param("collect-anonymous-statistics", "")
            param("report-as-test-mode", "")
        }
    }
}
