apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deploy
  labels:
    apps: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: rest-img:v1
          ports:
            - containerPort: 8083