name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - master
      - qodana
      - default

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      GRADLE_OPTS: "-Dfile.encoding=UTF-8"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3.3
        with:
          upload-result: true
          primary-cache-key: qodana-2024.3-${{ github.ref }}
          additional-cache-key: qodana-2024.3-refs/heads/qodana
        #        with:
#          primary-cache-key: qodana-2024.3-${{ github.event.repository.default_branch }}
#          use-caches: ${{ (github.ref_name == github.event.repository.default_branch) && 'true' || 'false' }}
        env:
          QODANA_TOKEN:  ${{ secrets.QODANA_TOKEN }}
