name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - master
      - qodana
      - default

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        uses: JetBrains/qodana-action@v2024.3.3
        with:
          primary-cache-key: qodana-2024.3-${{ github.event.repository.default_branch }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: 'Qodana Scan other'
        if: ${{ github.ref != github.event.repository.default_branch }}
        uses: JetBrains/qodana-action@v2024.3.3
        with:
          cache-default-branch-only: true
          cache-dir: ""
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}