name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - coverage

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzam94cSIsInByb2plY3QiOiJBT3JrZCIsInRva2VuIjoiM29NYWcifQ.uz74zIRZa1OOaEGZtXvKIrbqRnzwe1qraC8KSvllb48