name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - master
      - qodana

jobs:
  qodana:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@next
        with:
          pr-mode: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}